### ISSUE TITLE
smurf with rails 3.1

### ISSUE THREAD

**Issue by ippa** [thumblemonks/smurf#21]
Any plans of supporting rails 3.1? I'm far from sold on the asset pipeline but still want js/css compression.
## Now I get this:

undefined method `join_asset_file_contents' for module`ActionView::Helpers::AssetTagHelper'

0   /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/core_ext/module/aliasing.rb  31  in `alias_method'
1   /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/core_ext/module/aliasing.rb  31  in`alias_method_chain'
2   /usr/local/lib/ruby/gems/1.9.1/gems/smurf-1.0.8/lib/smurf.rb    15  in `'

**Comment by peppyheppy** [comment]
Sorry for the late response. Does smurf not work with rails 3.1? I haven't used it recently with my latest rails apps so I can't confirm either way. 

Unfortunately, I don't have any plans to add support for rails 3.1, but I would gladly accept a pull request from you or anyone who wants to add 3.1 support.
